---
title:  'Group Assignment - Python Programming'
subtitle: 'Web Scraping and User Interfaces'
author: [Sanhy Van Kilia - , Savinay Singh - , James Murray - 13879046]  
keywords: [Python, GUI, Web Scraping, ]
abstract: 
  This is the abstract,
  
  Make sure you type this after the paper is written. 

## Titlepage Info
titlepage: true
titlepage-logo: ./images/title_image.jpeg
logo-width: 150mm
titlepage-color: "e5e5e5"
## Table of Contents 
toc: true 
toc-own-page: true 
lof: true
lot: true

## bibliography is on the first line of yaml data for the paper itself - this enables the citepro for pandoc to act as a reference manager when researching and typing 
footnotes-pretty: true 
## Command in terminal is

# pandoc --citeproc report.md -o report.pdf --template eisvogel meta.yaml
--- 